- README.md
I've implemented UF2 for the Cypress FX2 chips (usually found on FPGA developer boards and such). This PR adds a family ID.
> Add family ID for Cypress FX2

- README.md
Add two new device ids.
In the future, this list might grow very large and I would suggest putting all the ids in a header file.
> added new ids for stm32f4 series

- utils/uf2conv.py
This trailing dot makes it less convenient to copy-and-paste the uf2 filename into other terminal commands.
> uf2conv: eliminate trailing dot on filename

- utils/uf2conv.py
I've been using `uf2conv.py` for some bootloader experiments because it's a nice tool with a great command line interface. I noticed it gets very slow (> linearly) with large files. Here is a quick repro (on Python 3.8.5):
```bash
$ cd uf2/utils
$ dd if=/dev/urandom of=rand.bin bs=16M count=1
$ time python3 uf2conv.py rand.bin -o rand.uf2
Converting to uf2, output size: 33554432, start address: 0x2000
Wrote 33554432 bytes to rand.uf2
real	4m30.839s
user	1m45.575s
sys	2m44.299s
```
This patch replaces the repeated concatenation of `bytes` objects in `convert_to_uf2()` and `convert_from_uf2()` with a `b"".join()`:
```bash
$ git checkout fix_byte_concat 
$ time python3 uf2conv.py rand.bin -o rand.uf2
Converting to uf2, output size: 33554432, start address: 0x2000
Wrote 33554432 bytes to …
```
> uf2conv.py: Fix O(n^2) concatenation in convert_to_uf2 and convert_from_uf2

- README.md
The IDs were generated randomly with https://microsoft.github.io/uf2/patcher/.
> Add family IDs for missing chips of Espressif

- utils/uf2conv.py
This PR adds `bindata_len` for carray coversion which is very handy for platform where the actual bootloader size is desired. Following is example output
```
const unsigned long bindata_len = 127760;
const unsigned char bindata[] __attribute__((aligned(16))) = {
0xe9, 0x06, 0x02, 0x2f, 0xa8, 0x2d, 0x02, 0x40, 0xee, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
```
> add bindata_len in carray conversion

- README.md
- utils/uf2conv.py
This PR add ESP32S2 family `0xbfdd4eee` which is generated randomly with recommended [patcher script](https://microsoft.github.io/uf2/patcher/) and currently is used by https://github.com/adafruit/tinyuf2 for esp32s2. 
~This also adds `bindata_len` for carray coversion which is very handy for platform where the actual bootloader size is desired.~ 
~PS: I am piggy packed 2 features in one PR since the modification is simple enough. Let me know if you want to separate them or want to make any adjustment.~
> add ESP32S2 family ID

- README.md
The ID was generated by https://microsoft.github.io/uf2/patcher/.
> Add ID generated for ESP32-S3

- README.md
- utils/uf2conv.py
Hi,
This PR adds a UF2 ID for RP2040. We generated the ID randomly using the recommended bash expression.
The UF2 bootloader is in the boot ROM, so unfortunately we can't change the ID at this point.
> Add RP2040 family ID

- utils/uf2conv.py
When invoked to deploy a uf2 image this currently emits something like
Converting to uf2, output size: 36864, start address: 0x2000
which misrepresents both the size and the start address and suggests
more conversion is happening.  Don't print anything about converting
in this case; also change to "converted" since the message is
displayed after the conversion completes.
> avoid misleading status message

- README.md
I've made a new UF2 bootloader for the STM32H7 with ChibiOS, see https://github.com/striso/uf2-ChibiOS
Since the STM32H7 is/was not well supported by libopencm3 I switched to ChibiOS, which has as nice fast HAL.
I've added some new features to expose files from the loaded firmware to the UF2 drive, for example a current firmware version file.
CF2 and webUSB are not supported. 
I'm also using some new family id's, but since I'm using them for specific hardware instead of the general chip I don't think they need to be added to uf2families.json, what do you think?
> Add link to new UF2 implementation for STM32H7

- utils/uf2families.json
The IDs were generated by the random number generator at https://microsoft.github.io/uf2/patcher.
> Add IDs for ESP32-C2 and ESP32-H2

- utils/uf2families.json
Working on a [tinyuf2 implementation](https://github.com/KarlK90/tinyuf2/tree/gd32vf103-support) for that chip, which is already functional. The family id was generated via CF2 patcher.
> Add GigaDevice GD32VF103 family ids

- utils/uf2conv.py
Basically what it says in the title. Use case for me is that I can easily discard or redirect error messages and only want pass on the stdout messages to the user.
> Print uf2conv errors to stderr instead of stdout

- utils/uf2conv.md
- utils/uf2conv.py
New --wait option for uf2conv.py to make automated and batch flashing easier.
With --wait it waits until a uf2 drive is connected, then flashes the file and exits.
I've done a bit of cleanup/restructuring of the code and updated the docs in advance in order to work on a clean base.
Thanks!
> Add option to wait for device to flash to uf2conv.py

- utils/uf2families.json
As the title, this PR adds a UF2 family ID for Sipeed MaixPlay-U4. We generated the ID randomly using the recommended bash expression.
> Add family ID for Sipeed MaixPlay-U4

- utils/uf2conv.py
Reproduce with:
```
echo -n foo12345679 > foo
echo -n bar12345679 > bar
./utils/uf2conv.py foo -c -b 0x100 -o foo.uf2
./utils/uf2conv.py bar -c -b 0x1000 -o bar.uf2
cat foo.uf2 bar.uf2 > combined.uf2
./utils/uf2conv.py -i combined.uf2
```
Would fail like this
```
--- UF2 File Header Info ---
All block flag values consistent, 0x0000
----------------------------
Traceback (most recent call last):
File "/home/zoid/clone/uf2/./utils/uf2conv.py", line 360, in <module>
main()
File "/home/zoid/clone/uf2/./utils/uf2conv.py", line 328, in main
convert_from_uf2(inpbuf)
File "/home/zoid/clone/uf2/./utils/uf2conv.py", line 109, in convert_from_uf2
return b"".join(outp)
TypeError: sequence item 1: expected a bytes-like object, int found
```
> utils/uf2conv.py: Fix padding with Python3

- utils/uf2families.json
Working on getting uf2 loading working with the Renesas RZ/A1LU (cortex_a). Added back to families.
> Added Renesas RZA1LU to families.

- utils/uf2conv.py
[QMK](https://github.com/qmk/qmk_firmware) currently uses `uf2conf.py` as part of its workflow to convert and eventually deploy firmware. It was noted by a few users on our Discord that on some Linux distributions, it failed to find the auto-mounted directory.
This PR adds the additional search directory `/run/media/<user>/` while also filtering to ensure the end list is only directories, and handling the uncaught exception when `/media/` does not exist.
> utils/uf2conv.py: Search for additional deployment locations

- utils/uf2families.json
The IDs were generated by the random number generator at https://microsoft.github.io/uf2/patcher.
> add IDs for ESP32-C6 and ESP32-P4

- utils/uf2families.json
I have written a UF2 upgrade program for STM32F411 and nRF52832. The nRF52832 does not have USB functionality, but it can be connected to the STM32F411 through a UART port. After the STM32F411 detects the UF2 blocks from nRF52832, it transfers them to the nRF52832 via the UART port.
I achieved the upgrade for both chips by copying the combined UF2 file for STM32F411 and nRF52832 onto the msc device of the upgraded version of STM32F411. Therefore, an ID needs to be assigned for the nRF52832 as well.
I believe that different chips with different memory capacities should be assigned different IDs. For example, STM32F411xE and STM32F411xC, nRF52832xxAA and nRF52832xxAB.
> add IDs for stm32f411xE stm32f411xC nrf52832xxAA nrf52832xxAB

- utils/uf2conv.py
In Python 3.12, unrecognized escape sequences now raise `SyntaxWarning`. So this line
https://github.com/microsoft/uf2/blob/17e70bf908e6abdf4f4acc50a9c84e5709ded2a9/utils/uf2conv.py#L211
is now erroneous: it needs to be `r'\s+'`.
Changed all regexps to be raw strings to avoid this problem for Python 3.12 and later.
This repo is used as a submodule in various downstream repos like [`uf2-samd21`](https://github.com/microsoft/uf2-samdx1), so those will need to be updated too.
@ladyada for interest
> Use raw strings for Python regexps to avoid Python 3.12 error

- utils/uf2families.json
IDs were generated by the random number generator at https://microsoft.github.io/uf2/patcher.
For reference:
- ESP32-C5: https://www.espressif.com/en/news/ESP32-C5
- ESP32-C61: https://www.espressif.com/en/news/ESP32-C61_SoC
> add IDs for ESP32-C5 and ESP32-C61

- utils/uf2families.json
The CH32V2xx and CH32V3xx series are RISC-V microcontrollers from Nanjing Qinheng Microelectronics (南京沁恒微电子). Their English website is at https://www.wch-ic.com/ .
I've written a UF2 bootloader for these parts (tested on the CH32V203C8T6, but the entire family seems to have a mostly-consistent memory map and the same flash interface) which I will be releasing in the next few days (after some code/docs cleanup) and want to reserve this family ID.
> Reserve family ID for WCH CH32V

- utils/uf2families.json
This PR adds a small number of UF2 family IDs for the new RP2350 microcontroller. They are used in mask ROM.
For code size reasons they are assigned sequentially from the RP2040 ID. Hopefully this is not an issue as the initial RP2040 ID was assigned randomly.
> Add UF2 families for RP2350

- utils/uf2families.json
ESPHome builds rtl8710bx firmware as an UF2 file. I noticed RTL8710B family is not in `uf2families.json`.
I found this mapping in libretuya project: https://github.com/blakadder/libretuya/blob/f63a11437126081dac49166bfa760403f8adbcd1/arduino/libretuya/core/ChipType.h#L10
> Add UF2 families for Realtek, Beken, Boufallo and Xradiotech

- utils/uf2families.json
Added random number as id for STM32H5 series microcontrollers (in a similar fashion to STM32H7 series)
> Add generic family id for STM32H5 series

- utils/uf2families.json
This PR add a random family id (0x820d9a5f) for Nordic nRF52820_xxAA series.
This ID is generated randomly from https://microsoft.github.io/uf2/patcher/
> Add generic family id for Nordic nRF52820_xxAA series.

- uf2.h
This PR adds defines for the flags described in README.md to uf2.h.
This way impementations do not have to define those outside of uf2.h, when the UF2 repository is added to a project as a submodule.
> add missing flagh defines to uf2.h

- utils/uf2families.json
- Added new IDs for the ESP32-H21 and ESP32-H4 additions to the ESP32 family.
- The random number generator at https://microsoft.github.io/uf2/patcher was used to generate the IDs.
> Add IDs for ESP32-H21 and ESP32-H4

- utils/uf2families.json
- Add IDs for Analog Devices USB capable MCUs MAX32690, MAX32666/5, MAX32650/1/2, and MAX78002.
- The random number generator at https://microsoft.github.io/uf2/patcher was used to generate the IDs.
> Add IDs for ADI MCUs

- utils/uf2conv.py
Hello everyone,
the RIOT OS uses the `uf2conv.py` script to program devices with the Adafruit nRF52 Bootloader.
Today we noticed some quirks:
1) Some distributions that don't necessarily use an automounter by default (like Arch Linux) don't necessarily use `/media` to mount devices but the more "tradutional" mount point `/mnt`. The `uf2conv.py` script currently does not search there.
2) When running `uf2conv.py` as root via `sudo`, it won't find any devices mounted by the user. This is because currently only the paths with `/media/${USER}` are checked. However `${USER}==root` when using `sudo`. Therefore this PR adds a check if `SUDO_USER` is defined in the environment and adds `/media/${SUDO_USER}` to the search path.
```
chris@W11nMate:~$ sudo python3
[sudo] password for chris:
Python …
```
> uf2conv: add more searchpaths, fix pathcheck
